#!/bin/bash
# This script automatically computes and draws a graph max(eigenvalue) vs. alpha0
# for every matrix listed (one graph per matrix list) and alpha_mode chosen
MATRIX_LIST="full_rank_opt_mat_NR25_NS25 opt_mat_NR25_NS50 opt_mat_NR50_NS25"
ALPHA_MODE="random_structure no_release_when_eat optimal_matrix"
SAVENAME="max_eigenvalues_variable_syntrophy"
ADDITIONAL_MODIF=""

for a in $ALPHA_MODE
do
  for matl in $MATRIX_LIST
  do
    CURRENT_NAME="${SAVENAME}_${a}_${matl}"
    if [ ! -z "${ADDITIONAL_MODIF}" ]
    then
      for add in $ADDITIONAL_MODIF
      do
        CURRENT_NAME="${CURRENT_NAME}_${add}"
      done
    fi
    FIRST_COMMAND="build/compute_largest_eigenvalue_at_equilibrium config/configuration.in path_to_save_file=data_output/${CURRENT_NAME}.out path_to_food_matrix=config/${matl}.in alpha_mode=${a} ${ADDITIONAL_MODIF}"
    FIRST_COMMAND="${FIRST_COMMAND} | ts \"[%Y-%m-%d %H:%M:%S]\""

    SECOND_COMMAND="python3 data_analysis/plot_max_eigenvalue_varying_alpha0.py data_output/${CURRENT_NAME}"

    COMMAND_NAME="${FIRST_COMMAND} && ${SECOND_COMMAND}"

    LOG_NAME="logs/${CURRENT_NAME}.log"
    ERR_LOG_NAME="logs/err_${CURRENT_NAME}.log"
    # execute command
    nohup sh -c "${COMMAND_NAME}" >${LOG_NAME} 2>${ERR_LOG_NAME} &
    # write command to log
    now="["$(date)"]"
    echo "${now} nohup sh -c \"${COMMAND_NAME}\" >${LOG_NAME} 2>${ERR_LOG_NAME} &" >> logs/commands.log
  done
done
echo "Launched commands in the background, please check appropriate log files for progress"
