#!/bin/bash

# get plot for given matrix
# nohup ./build/compute_average_extinctions ./config/configuration_comparison_NR25_NS25.in path_to_save_file=./data_output/average_extinctions_large.out path_to_food_matrix=./matrices/Nr25_Nc25/RandTrix_Nr25_Nc25_Nest0.3_Conn0.1296.txt > ./logs/av_ext_large.log &
# nohup ./build/compute_average_extinctions_window ./config/configuration_comparison_NR25_NS25.in path_to_save_file=./data_output/average_extinctions_window.out path_to_food_matrix=./matrices/Nr25_Nc25/RandTrix_Nr25_Nc25_Nest0.3_Conn0.1296.txt > ./logs/av_ext_window.log &
# get delta critical (split in 6)
nohup ./build/compute_critical_Delta ./config/configuration_comparison_NR25_NS25.in  path_to_food_matrix=./config/matrix_list_NR25_NS25_1.in path_to_save_file=./data_output/critical_delta_NR25_NS25_1.out |ts '[%Y-%m-%d %H:%M:%S]' > ./logs/critical_delta_1.log &
nohup ./build/compute_critical_Delta ./config/configuration_comparison_NR25_NS25.in  path_to_food_matrix=./config/matrix_list_NR25_NS25_2.in path_to_save_file=./data_output/critical_delta_NR25_NS25_2.out |ts '[%Y-%m-%d %H:%M:%S]'> ./logs/critical_delta_2.log &
nohup ./build/compute_critical_Delta ./config/configuration_comparison_NR25_NS25.in  path_to_food_matrix=./config/matrix_list_NR25_NS25_3.in path_to_save_file=./data_output/critical_delta_NR25_NS25_3.out |ts '[%Y-%m-%d %H:%M:%S]'> ./logs/critical_delta_3.log &
nohup ./build/compute_critical_Delta ./config/configuration_comparison_NR25_NS25.in  path_to_food_matrix=./config/matrix_list_NR25_NS25_4.in path_to_save_file=./data_output/critical_delta_NR25_NS25_4.out |ts '[%Y-%m-%d %H:%M:%S]'> ./logs/critical_delta_4.log &
nohup ./build/compute_critical_Delta ./config/configuration_comparison_NR25_NS25.in  path_to_food_matrix=./config/matrix_list_NR25_NS25_5.in path_to_save_file=./data_output/critical_delta_NR25_NS25_5.out |ts '[%Y-%m-%d %H:%M:%S]'> ./logs/critical_delta_5.log &
nohup ./build/compute_critical_Delta ./config/configuration_comparison_NR25_NS25.in  path_to_food_matrix=./config/matrix_list_NR25_NS25_6.in path_to_save_file=./data_output/critical_delta_NR25_NS25_6.out |ts '[%Y-%m-%d %H:%M:%S]'> ./logs/critical_delta_6.log &
