#!/bin/bash

# get plot for given matrix
# nohup ./build/compute_average_extinctions ./config/configuration_comparison_NR25_NS25.in path_to_save_file=./data_output/average_extinctions_large.out path_to_food_matrix=./matrices/Nr25_Nc25/RandTrix_Nr25_Nc25_Nest0.3_Conn0.1296.txt > ./logs/av_ext_large.log &
# nohup ./build/compute_average_extinctions_window ./config/configuration_comparison_NR25_NS25.in path_to_save_file=./data_output/average_extinctions_window.out path_to_food_matrix=./matrices/Nr25_Nc25/RandTrix_Nr25_Nc25_Nest0.3_Conn0.1296.txt > ./logs/av_ext_window.log &
# get delta critical (split in 6)
