#!/bin/bash

CORES=$1
python3 additional_scripts/run_structural_stability_computations.py $CORES
echo "Launched commands on" $CORES "cores, please check the appropriate logs files in logs folder if needed"
