#!/bin/bash

CORES=$1
# config file folder, then potential additional parameters
FOLDER=$2
ADDITIONAL_PARAMS=""
for ((i=3; i <= $#; i++))
do
  ADDITIONAL_PARAMS="${ADDITIONAL_PARAMS} ${!i}"
done
python3 additional_scripts/run_structural_stability_computations.py $CORES $FOLDER $ADDITIONAL_PARAMS
