#!bin/bash

./build/compute_critical_Delta ./config/configuration_comparison_NR25_NS25.in  path_to_food_matrix=./config/matrix_list_NR25_NS25_test.in path_to_save_file=./data_output/critical_delta_NR25_NS25_test.out
