#!/bin/bash

# This script generates a file which, when run, will find the optimal syntrophy matrix
# for every consumption matrix on the MATRIX_LIST file
# given in the configuration file CONFIGURATION_FILE.

# The file generated will be placed in the ./commands folder and named after
# the variable COMMAND_FILE

# Example for NR=NS=25
# Name of the matrix list within the matrix_list folder
MATRIX_LIST_FOLDER="matrix_list/Nr25_Nc25/consumption"
MATRIX_LIST_FILENAME="full_rank_opt_consumption_mat_NR25_NS25"
# intra specific syntrophy, can be either "allowed" or "not_allowed"
INTRA_SPE_SYN="allowed"
# Monte Carlo mode: A_only to find the optimal A for a given G or both_modified to find both G and A for a given G connectance
MCMODE="A_only"
# additional modifications of the default metaparameters values
ADDITIONAL_MODIF="gamma0=1 alpha0=1"
# additional suffix in the final name
SAVENAME="opt_mat"
# we would like to run 4 runs of the MC algorithm of each matrix
SEED_NUMBER=($(seq 0 1 3))
# name of the command file generated in the ./commands folder
COMMAND_FILE="optimize_matrices"
# other metaparameters have default value
CONFIGURATION_FILE="config/configuration.in"


##### END OF CONFIGURABLE PART #######

# And possible modifications for NR=50 and NS=25
#MATRIX_LIST="full_rank_opt_consumption_mat_NR50_NS25"
#ALPHA_MODE="random_structure no_release_when_eat optimal_matrix fully_connected"
#SAVENAME="local_dynamical_stability_NR50_NS25"
#ADDITIONAL_MODIF="NR=50 NS=25"

# first clear all previous contents of the commands file
rm commands/${COMMAND_FILE}.txt
for seed in ${SEED_NUMBER[@]}
do
  for intra in $INTRA_SPE_SYN
  do
    for mcmode in $MCMODE
    do
      for matl in $MATRIX_LIST_FILENAME
      do
        CURRENT_NAME=${SAVENAME}_"intra_specific_syntrophy="${intra}_"seed_number="${seed}
        if [ ! -z "${ADDITIONAL_MODIF}" ]
          then
            for add in $ADDITIONAL_MODIF
            do
              CURRENT_NAME="${CURRENT_NAME}_${add}"
            done
          fi

          FIRST_COMMAND="build/find_optimal_syntrophy_matrices ${CONFIGURATION_FILE} path_to_food_matrix=${MATRIX_LIST_FOLDER}/${matl}.in mcmode=${mcmode} alpha0=${alpha} intra_specific_syntrophy=${intra} path_to_save_file=${CURRENT_NAME} seed_number=${seed} ${ADDITIONAL_MODIF}"
          FIRST_COMMAND="${FIRST_COMMAND} | ts '[%Y-%m-%d %H:%M:%S]' "

          COMMAND_NAME="${FIRST_COMMAND}"

          LOG_NAME="logs/${COMMAND_FILE}_${matl}_${seed}.log"
          ERR_LOG_NAME="logs/err_${COMMAND_FILE}_${matl}_${seed}.log"
          # execute command
          #nohup sh -c "${COMMAND_NAME}" >${LOG_NAME} 2>${ERR_LOG_NAME} &
          echo "${COMMAND_NAME} > ${LOG_NAME} 2>${ERR_LOG_NAME}" >> commands/${COMMAND_FILE}.txt
          # write command to log
          now="["$(date)"]"
          echo "${now} nohup sh -c \"${COMMAND_NAME}\" >${LOG_NAME} 2>${ERR_LOG_NAME} &" >> logs/commands.log
        done
    done
  done
done
