#!/bin/bash

# This script generates a file which, when run, finds the critical delta (structural stability) of feasible
# systems for every consumption matrix on the MATRIX_LIST file, with alpha in mode ALPHA_MODE,
# for every value of alpha0 in the ALPHA_VALS list, with the other metaparameters
# given in the configuration file CONFIGURATION_FILE.

# The file generated will be placed in the ./commands folder and named after
# the variable COMMAND_FILE

# Example for NR=NS=25
MATRIX_LIST="full_rank_opt_consumption_mat_NR25_NS25"
ALPHA_MODE="optimal_matrix"
SAVENAME=""
OPTIMAL_MATRIX_FOLDER="Metamatrices"
ALPHA_VALS="0 0.014"
ADDITIONAL_MODIF="verbose-level=1"
NR=25
NS=25

CONFIGURATION_FILE="config/configuration.in"
COMMAND_FILE="feasibility_NR25_NS25_opt_mat"

# And possible modifications for NR=50 and NS=25
#MATRIX_LIST="full_rank_opt_consumption_mat_NR50_NS25"
#ALPHA_MODE="random_structure no_release_when_eat optimal_matrix fully_connected"
#SAVENAME="local_dynamical_stability_NR50_NS25"
#ADDITIONAL_MODIF="NR=50 NS=25"
#ALPHA_VALS="0"

# first clear all previous contents of the commands file
rm commands/${COMMAND_FILE}

while read F; do
  echo ${F}
done <matrix_list/full_rank_opt_consumption_mat_NR25_NS25.in
