#!/bin/bash

# This script generates a file which, when run, computes the percentage of dynamically stable systems for every
# matrix on the MATRIX_LIST file, with alpha in mode ALPHA_MODE, for every
# value of alpha0 in the ALPHA_VALS list.

# Example for NR=NS=25
CONSUMPTION_MATRIX_LIST_FOLDER="matrix_list/Nr25_Nc25/consumption"
CONSUMPTION_MATRIX_LIST_FILENAME="full_rank_opt_consumption_mat_NR25_NS25"

# SYNTROPHY_MATRIX_FOLDER is unused if ALPHA_MODE is set to random structure
SYNTROPHY_MATRIX_FOLDER="matrices/Nr25_Nc25/syntrophy/optimized/Metamatrices"
ALPHA_MODE="random_structure fully_connected optimal_matrix"
ALPHA_VALS="0"

ADDITIONAL_MODIF="verbose-level=1"
NR=25
NS=25

CONFIGURATION_FILE="config/default_configuration.in"
COMMAND_FILE="study_test_no_syntrophy"
SAVENAME="all_data_NR25_NS25"
BUILD_NAME="study_ecological_systems"

# first clear all previous contents of the commands file
rm commands/${COMMAND_FILE}.txt


for a in $ALPHA_MODE
do
  for matl in $CONSUMPTION_MATRIX_LIST_FILENAME
  do
    for alpha0 in $ALPHA_VALS
    do
      CURRENT_NAME="${SAVENAME}"
      if [ ! -z "${ADDITIONAL_MODIF}" ]
      then
        for add in $ADDITIONAL_MODIF
        do
          CURRENT_NAME="${CURRENT_NAME}_${add}"
        done
      fi

      FIRST_COMMAND="build/${BUILD_NAME} ${CONFIGURATION_FILE} path_to_save_file=results/${CURRENT_NAME}.out path_to_food_matrix=${CONSUMPTION_MATRIX_LIST_FOLDER}/${matl}.in alpha_mode=${a} path_to_syntrophy_matrix=${SYNTROPHY_MATRIX_FOLDER} NR=${NR} NS=${NS} alpha0=${alpha0} ${ADDITIONAL_MODIF}"
      #FIRST_COMMAND="${FIRST_COMMAND} | ts '[%Y-%m-%d %H:%M:%S]'"

      COMMAND_NAME="${FIRST_COMMAND}"

      #LOG_NAME="logs/${COMMAND_FILE}.log"
      #ERR_LOG_NAME="logs/err_${COMMAND_FILE}.log"

      echo "${COMMAND_NAME}" >> commands/${COMMAND_FILE}.txt
      # write command to log
      now="["$(date)"]"
      echo "${now} ${COMMAND_NAME}" >> logs/commands.log
    done
  done
done
#echo "Launched commands in the background, please check appropriate log files for progress"
